apiVersion: v1
kind: Service
metadata:
  name: cornelia-loadbalancer-service
  namespace: cornelia-eks-activity
spec:
  type: LoadBalancer
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678