apiVersion: v1
kind: Service
metadata:
  name: cornelia-clusterip-service
  namespace: cornelia-eks-activity
spec:
  type: ClusterIP
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5678